### ISSUE TITLE
`ramble workspace setup` modifies `{hash:7}` in Spack config file

### ISSUE THREAD

**Issue by scheibelp** [GoogleCloudPlatform/ramble#444]
### Steps to reproduce

I have a ramble workspace with:

cat test-saxpy-oslic-bug/saxpy/openmp/nosite-x86_64/workspace/configs/auxiliary_software_files/config.yaml

```
config:
    install_tree:
      projections:
        all: '{name}-{version}-{hash:7}'
```

I run `ramble -P -D /.../test-saxpy-oslic-bug/saxpy/openmp/nosite-x86_64/workspace workspace setup`

Then If I look at `test-saxpy-oslic-bug/saxpy/openmp/nosite-x86_64/workspace/software/saxpy.problem/config.yaml`:

```
config:
    install_tree:
      projections:
        all: '{name}-{version}-hash  
```

the `{}` were removed from `{hash:7}`

(to fully reproduce: I generated this Ramble workspace with Benchpark ``./bin/benchpark setup saxpy/openmp nosite-x86_64 `pwd`/test-saxpy-oslic-bug`` after adding the first config file to `configs/nosite-x86_64/auxiliary_software_files/config.yaml `)

### Error message

(no error message, but the problem is shown above)

### Information on your system

* **Ramble:** 0.4.0 (3d6d2670435c704ca815ae13abe49b10c5111638)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell

### General information

- [X] I have run `ramble debug report` and reported the version of Ramble/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
This is not a major problem for me: if I use `{hash}` instead of `{hash:7}` everything works fine.

**Comment by douglasjacobsen** [comment]
@scheibelp Thanks for the reproducer.

I think that given we want to support the expansion of things like:  `{2:03d}` this becomes trickier to automatically understand the intent of your expansion string.

For now, I think the case you want should be explicitly escaped, since you really want the `{` and `}` characters in the output.

Something like this should work:

```
config:
    install_tree:
      projections:
        all: '\{name\}-\{version\}-\{hash:7\}'
```

For consistency, I escaped the `name` and `version` ones as well. Though, those are not strictly necessary since they don't have a format string that is removed, it makes the pattern that is applied a bit more transparent.
