### ISSUE TITLE
Workspace env-vars and variables are not being set in experiments

### ISSUE THREAD

**Issue by douglasjacobsen** [GoogleCloudPlatform/ramble#66]
### Steps to reproduce

```
ramble:
  mpi:
    command: mpirun
    args:
    - '-n'
    - '{n_ranks}'
    - '-ppn'
    - '{processes_per_node}'
    - '-hostfile'
    - 'hostfile'
  batch:
    submit: 'batch_submit {execute_experiment}'
  variables:
    partition: 'part1'
    processes_per_node: '16'
    n_threads: '1'
    ws_var: 'workspace'
  env-vars:
    set:
      WS_LEVEL: 'TEST'
  applications:
    interleved-env-vars:
      variables:
        app_var: 'application'
      env-vars:
        set:
          APP_LEVEL: 'TEST'
      workloads:
        test_wl:
          variables:
            wl_var: 'workload'
          env-vars:
            set:
              WL_LEVEL: 'TEST'
          experiments:
            simple_test:
              variables:
                n_nodes: 1
                exp_var: 'experiment'
              env-vars:
                set:
                  EXP_LEVEL: '{ws_var}.{app_var}.{wl_var}.{exp_var}'
spack:
  concretized: true
  compilers: {}
  mpi_libraries: {}
  applications: {}
```

### Error message

With `ramble -m workspace setup --dry-run` does not generate the workspace variables and env-vars properly.

### Information on your system

```
└─▪ ramble debug report
* **Ramble:** 0.0.1 (069fd9be7de335d55b65b3b2ace0e362b93822f1)
* **Python:** 3.10.8
* **Platform:** linux-debianrodete-skylake
```

### General information

- [X] I have run `ramble debug report` and reported the version of Ramble/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
