### ISSUE TITLE
Support dependencies within `mpi_libraries` portion of ramble workspace spack schema

### ISSUE THREAD

**Issue by sudheerchunduri** [GoogleCloudPlatform/ramble#76]
### Summary

The spack configuration specification within Ramble workspace definition allow the following specifications: `compilers`, `mpi_libraries` and `applications`. Right now, `mpi_libraries` does not support specifying dependencies, example, to have an MPI version built using a specific `libfabric` dependency.

### Description

The specification I am looking for is:

```
mpi_libraries:
    mpich-libfabric:
      libfabric-main:
        base: libfabric
        version: main
        variants: fabrics=psm3,tcp,sockets
      mpich:
        base: mpich
        version: 4.1.1
        target: x86_64
        variants: device==ch4 netmod==ofi
        dependencies:
        - libfabric-main
 ```

### Additional information

Right now, I was able to achieve the enforcement of dependency by specifying within `applications` as in 

```
spack:
  applications:
    app_name:
      libfabric:
        base: libfabric
        version: main
```
but it is more intuitive to specify dependency within `mpi_libraries`. 

Ramble version is 0.0.1.

### General information

- [X] I have run `ramble --version` and reported the version of Ramble
- [X] I have searched the issues of this repo and believe this is not a duplicate
