### ISSUE TITLE
`workspace concretize` does not preserve config comments

### ISSUE THREAD

**Issue by douglasjacobsen** [GoogleCloudPlatform/ramble#82]
### Steps to reproduce

Create a workspace with the following ramble.yaml:
```yaml
ramble:
  mpi:
    command: mpirun
    args: []
  batch:
    submit: '{execute_experiment}'
  variables:
    partition: [part1, part2]
    processes_per_node: ['16', '36']
    n_ranks: '{processes_per_node}*{n_nodes}'
    n_threads: '1'
  applications:
    # COMMENT TEST
    wrfv4:
      variables:
        spec_name: wrfv4
      workloads:
        CONUS_12km:
          experiments:
            scaling_{n_nodes}_{partition}_{spec_name}:
              variables:
                n_nodes: ['1', '2', '4', '8', '16']
spack:
  concretized: false
  compilers: {}
  mpi_libraries: {}
  applications: {}
```

`ramble workspace concretize`
`grep "COMMENT TEST" <path_to_ramble.yaml>` should contain nothing.

### Error message

No error message, just odd behavior.

### Information on your system

```
└─▪ ramble debug report
* **Ramble:** 0.0.1 (d8b86c7e36e4ee7bfece3c399adf2750e3b2f837)
* **Python:** 3.10.8
* **Platform:** linux-debianrodete-skylake
```

### General information

- [X] I have run `ramble debug report` and reported the version of Ramble/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
