### ISSUE TITLE
ramble spack package paths not expanding in experiment series definitions

### ISSUE THREAD

**Issue by sudheerchunduri** [GoogleCloudPlatform/ramble#95]
### Steps to reproduce

```
ramble workspace create wrfv4_tests -c wrf4_tests.yaml
ramble workspace activate wrfv4_tests 
ramble workspace setup
```

The `wrf4_tests.yaml` is:
```
# Ramble config to reproduce the WRFv4
# {wrf} should be expanded into the spack built path for wrf binary
# but it is not getting expanded into for all the experiment cases
ramble:
  mpi:
    command: mpirun
    args:
    - -n
    - '{n_ranks}'
    - -ppn
    - '{processes_per_node}'
    - -hostfile
    - /shared/hostfile
  batch:
    submit: '{execute_experiment} 2> {experiment_run_dir}/{experiment_name}.err'
  variables:
    n_ranks: '{processes_per_node}*{n_nodes}'
    psm3_library_path: /shared/psm3-11.4.1.1-2/
  applications:
    wrfv4:
      workloads:
        CONUS_2p5km:
          variables:
            iter: ['1', '2']
            processes_per_node: ['88']
            n_nodes: ['2', '4', '8', '16']
          experiments:
            impi2021-t1_{processes_per_node}_{n_nodes}_{iter}:
              variables:
                spec_name: wrfv4-impi2021-internal-ofi
              matrices:
              - matrix_a:
                - n_nodes
                - iter
            impi2021-t2-internal-ofi_{processes_per_node}_{n_nodes}_{iter}:
              env-vars:
                set:
                  FI_PROVIDER: tcp
              variables:
                spec_name: wrfv4-impi2021-internal-ofi
              matrices:
              - matrix_a:
                - n_nodes
                - iter
spack:
  concretized: true
  compilers:
    gcc9:
      base: gcc
      version: 9.3.0
      target: cascadelake
    gcc8:
      base: gcc
      version: 8.2.0
      target: x86_64
  mpi_libraries:
    impi2021-internal-ofi:
      base: intel-oneapi-mpi
      version: 2021.8.0
      compiler: gcc9
      target: cascadelake
  applications:
    wrfv4-impi2021-internal-ofi:
      wrf:
        base: wrf
        version: 4.4
        variants: build_type=dm+sm compile_type=em_real nesting=basic ~chem
        compiler: gcc9
        mpi: impi2021-internal-ofi
        target: cascadelake
```

In the `experiments` that is created using the above `wrf4_tests.yaml` config file, the `{wrf}` variable is not expanded as required. It is only expanded in one of the experiment, but for the others `{wrf}` is not expanded. `{wrf}` is used as part of ```
    executable('copy', template=['cp -R {input_path}/* {experiment_run_dir}/.',
                                 'ln -s {wrf}/run/* {experiment_run_dir}/.'],
               use_mpi=False)
``` in ramble config for `wrfv4` 

### Information on your system

* **Ramble:** 0.0.1
* **Python:** 3.9.12

### General information

- [X] I have run `ramble debug report` and reported the version of Ramble/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
