### ISSUE TITLE
Incorrect setting of the environment variables

### ISSUE THREAD

**Issue by sudheerchunduri** [GoogleCloudPlatform/ramble#96]
### Steps to reproduce

User specified environment variables are overwritten by a Spack package:

In the example below, FI_PROVIDER_PATH should be set as specified by the user.
Using the below ramble config file, 

```
ramble:
  mpi:
    command: mpirun
    args:
    - -n
    - '{n_ranks}'
    - -ppn
    - '{processes_per_node}'
    - -hostfile
    - /shared/hostfile
  batch:
    submit: '{execute_experiment} 2> {experiment_run_dir}/{experiment_name}.err'
  variables:
    n_ranks: '{processes_per_node}*{n_nodes}'
    net_library_path: /shared/intel-2023.0/mpi/latest/libfabric/lib/prov/
  applications:
    wrfv4:
      workloads:
        CONUS_2p5km:
          variables:
            iter: ['1', '2']
            processes_per_node: ['88']
            n_nodes: ['2', '4', '8', '16']
          experiments:
            impi2021-net_{processes_per_node}_{n_nodes}_{iter}:
              env-vars:
                set:
                  I_MPI_ADJUST_BCAST: '8'
                  I_MPI_ADJUST_ALLREDUCE: '10'
                  FI_PROVIDER: net
                  FI_PROVIDER_PATH: '{net_library_path}'
              variables:
                spec_name: wrfv4-impi2021-internal-ofi
              matrices:
              - matrix_a:
                - n_nodes
                - iter
spack:
  concretized: true
  compilers:
    gcc9:
      base: gcc
      version: 9.3.0
      target: cascadelake
    gcc8:
      base: gcc
      version: 8.2.0
      target: cascadelake
  mpi_libraries:
    impi2021-internal-ofi:
      base: intel-oneapi-mpi
      version: 2021.8.0
      compiler: gcc9
      target: cascadelake
  applications:
    wrfv4-impi2021-internal-ofi:
      wrf:
        base: wrf
        version: 4.4
        variants: build_type=dm+sm compile_type=em_real nesting=basic ~chem
        compiler: gcc9
        mpi: impi2021-internal-ofi
        target: cascadelake
```

however, the environment variables are set (using the `export` commands) before setting the spack environment as 
```
export FI_PROVIDER=net;
export FI_PROVIDER_PATH=/shared/intel-2023.0/mpi/latest/libfabric/lib/prov/;
. /shared/spack/share/spack/setup-env.sh
spack env activate /shared/ramble/var/ramble/workspaces/test/software/exp1
```
in the `execute_experiment` script.

In the above case, `FI_PROVIDER_PATH` is appended by the Intel MPI library that is loaded with the SPACK. However, that results in picking the incorrect provider as the order of the appending is not as desired. 

Manually, editing the `execute_experiment` as below results in the desired behavior and picks the right provider.
```
. /shared/spack/share/spack/setup-env.sh
spack env activate /shared/ramble/var/ramble/workspaces/test/software/exp1
export FI_PROVIDER=net;
export FI_PROVIDER_PATH=/shared/intel-2023.0/mpi/latest/libfabric/lib/prov/;
```

### Information on your system

* **Ramble:** 0.0.1
* **Python:** 3.9.12

### General information

- [X] I have run `ramble debug report` and reported the version of Ramble/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output
